# Generated by Django 2.2.12 on 2020-04-19 08:58

import config.storage_backends
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance_sheet', models.FileField(storage=config.storage_backends.PrivateMediaStorage(), upload_to='balance_sheets/pdfs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('csv_file', models.FileField(storage=config.storage_backends.PrivateMediaStorage(), upload_to='balance_sheets/csv', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])])),
                ('query_value', models.IntegerField(blank=True, null=True)),
                ('query_variable', models.CharField(blank=True, max_length=64, null=True)),
                ('query_year', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'balance_sheet',
            },
        ),
    ]
